### ISSUE TITLE
✏️ Typo on Pikaday doc

### ISSUE THREAD

**Issue by dustinmwang2104** [blade-ui-kit/docs#19]
Found a wrong class name on Pikaday documentation on `Setting Defaults` chapter.

`class Pikaday extends \BladeUIKit\Components\Forms\Pikaday` should be `class Pikaday extends \BladeUIKit\Components\Forms\Inputs\Pikaday`

![image](https://user-images.githubusercontent.com/7719701/128703908-22270e0b-0e16-4e91-8bc6-80fe78797c02.png)

**Comment by driesvints** [comment]
Thanks fixed!
